import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHandler,validateConfig} from '../server/core.mjs';
import {sqliteAdapter} from '../server/sqlite.mjs';
import {seed} from '../server/seed.mjs';
import {makeBlock} from '../public/prompt.js';
const origin='https://studio.example',setupToken='test-only-setup-key-32-characters-long',teamPassword='test-only-team-password',editorPassword='test-only-editor-password';
async function fixture(t){const dir=await mkdtemp(join(tmpdir(),'ncgcl-'));const db=sqliteAdapter(join(dir,'test.sqlite'));const files=new Map();const handler=createHandler({db,setupToken,storage:{put:async(k,b)=>{files.set(k,b);return '/uploaded/'+k;}},serveStatic:async()=>new Response('static')});t.after(async()=>{db.close();await rm(dir,{recursive:true,force:true});});const call=async(path,body,cookie='',extra={})=>{const r=await handler(new Request(origin+'/api/'+path,{method:body===undefined?'GET':'POST',headers:{Origin:origin,...(cookie?{Cookie:cookie}:{}),...extra},body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body)}));return {status:r.status,cookie:r.headers.get('set-cookie')?.split(';')[0],headers:r.headers,data:await r.json()};};const setup=await call('setup',{token:setupToken,teamPassword,editorPassword});assert.equal(setup.status,200);const login=await call('login',{role:'team',password:teamPassword});assert.equal(login.status,200);return {db,files,call,editor:setup.cookie,team:login.cookie};}
test('roles, CSRF protection and exports exclude credentials',async t=>{const f=await fixture(t);assert.equal((await f.call('standards')).status,401);const team=await f.call('standards',undefined,f.team);assert.equal(team.status,200);const changes=await f.call('changes',undefined,f.team);assert.deepEqual(changes.data,{version:1,revision:1});assert.equal((await f.call('changes')).status,401);assert.equal(team.data.draft,undefined);assert.equal(team.data.config.types.length,10);assert.equal((await f.call('export',undefined,f.team)).status,403);assert.equal((await f.call('standards',{action:'publish'},f.team)).status,403);assert.equal((await f.call('logout',{},f.team,{Origin:'https://evil.example'})).status,403);const ex=await f.call('export',undefined,f.editor);assert.equal(ex.status,200);assert.equal(ex.data.auth,undefined);assert.equal(JSON.stringify(ex.data).includes(editorPassword),false);assert.equal((await f.call('setup',{token:setupToken,teamPassword,editorPassword})).status,409);});
test('draft isolation, latest copy, atomic publication, stale editor protection and restore',async t=>{const f=await fixture(t);const before=(await f.call('standards',undefined,f.editor)).data;const config=structuredClone(before.draft);config.footerText='NEW FOOTER {{page}}';config.types.push({...config.types[0],id:'new-type',name:'New type'});const saved=await f.call('standards',{action:'save',revision:before.revision,config},f.editor);assert.equal(saved.status,200);assert.equal(saved.data.version,1);assert.notEqual((await f.call('standards',undefined,f.team)).data.config.footerText,config.footerText);assert.equal((await f.call('standards',{action:'publish',revision:before.revision,config,note:'stale'},f.editor)).status,409);const published=await f.call('standards',{action:'publish',revision:saved.data.revision,config,note:'New footer and type'},f.editor);assert.equal(published.status,200);assert.equal(published.data.version,2);const block=await f.call('block',{type:'new-type'},f.team);assert.equal(block.data.version,2);assert.match(block.data.text,/NEW FOOTER/);assert.match(block.data.text,/https:\/\/studio.example\/assets\/ncgcl-logo.png/);const restore=await f.call('standards',{action:'restore',version:1,revision:published.data.revision},f.editor);assert.equal(restore.status,200);assert.equal(restore.data.draft.footerText,before.draft.footerText);assert.equal(restore.data.config.footerText,config.footerText);});
test('concurrent writes cannot silently overwrite one another',async t=>{const f=await fixture(t);const start=(await f.call('standards',undefined,f.editor)).data;const a=structuredClone(start.draft),b=structuredClone(a);a.footerText='A';b.footerText='B';const out=await Promise.all([f.call('standards',{action:'save',revision:start.revision,config:a},f.editor),f.call('standards',{action:'save',revision:start.revision,config:b},f.editor)]);assert.deepEqual(out.map(r=>r.status).sort(),[200,409]);});
test('password rotation invalidates only the selected role and logout revokes session',async t=>{const f=await fixture(t);const changed=await f.call('passwords',{role:'team',currentPassword:editorPassword,password:'replacement-team-password'},f.editor);assert.equal(changed.status,200);assert.equal((await f.call('standards',undefined,f.team)).status,401);assert.equal((await f.call('changes',undefined,f.team)).status,401);assert.equal((await f.call('standards',undefined,f.editor)).status,200);assert.equal((await f.call('login',{role:'team',password:teamPassword})).status,401);const newTeam=await f.call('login',{role:'team',password:'replacement-team-password'});assert.equal(newTeam.status,200);assert.equal((await f.call('logout',{},newTeam.cookie)).status,200);assert.equal((await f.call('standards',undefined,newTeam.cookie)).status,401);const editorChange=await f.call('passwords',{role:'editor',currentPassword:editorPassword,password:'replacement-editor-password'},f.editor);assert.equal(editorChange.status,200);assert.equal(editorChange.data.signOut,true);assert.equal((await f.call('standards',undefined,f.editor)).status,401);});
test('upload restrictions and immutable filenames preserve older assets',async t=>{const f=await fixture(t);const pdf=()=>{const body=new FormData();body.append('file',new Blob(['%PDF-1.4\nfixture'],{type:'application/pdf'}),'reference.pdf');return body;};assert.equal((await f.call('assets',pdf(),f.team)).status,403);const a=await f.call('assets',pdf(),f.editor),b=await f.call('assets',pdf(),f.editor);assert.equal(a.status,200);assert.equal(b.status,200);assert.notEqual(a.data.url,b.data.url);assert.equal(f.files.size,2);const wrong=new FormData();wrong.append('file',new Blob(['<script>bad</script>']),'logo.png');assert.equal((await f.call('assets',wrong,f.editor)).status,400);});
test('validation prevents malformed imports and script URLs',async t=>{const f=await fixture(t);assert.equal((await f.call('validate',{config:{types:[],assets:[]}},f.editor)).status,400);const bad=structuredClone(seed);bad.assets[0].url='javascript:alert(1)';assert.throws(()=>validateConfig(bad));bad.assets[0].url='https://x.example/logo.png';bad.types.forEach(x=>x.active=false);assert.throws(()=>validateConfig(bad));assert.equal((await f.call('validate',{config:seed},f.editor)).status,200);});
test('authentication throttling persists in database',async t=>{const f=await fixture(t);for(let i=0;i<11;i++)assert.equal((await f.call('login',{role:'team',password:'incorrect'})).status,401);assert.equal((await f.call('login',{role:'team',password:teamPassword})).status,429);});
test('prompt needs no brief and adapts to slides without rewriting substance',()=>{const block=makeBlock(seed,'research-note',{},1,origin);assert.doesNotMatch(block,/DOCUMENT DETAILS/);assert.match(block,/Preserve my substantive task/);assert.match(block,/ask me to attach it/);const slides=makeBlock(seed,'presentation',{format:'PowerPoint (.pptx)',title:'A presentation'},2,origin);assert.match(slides,/slide masters/);assert.match(slides,/Document title: A presentation/);assert.doesNotMatch(slides,/Apply actual Word paragraph/);});
