export const seed={
 organisation:'National Credit Guarantee Company Limited (NCGCL)',blue:'#035076',green:'#39A949',secondary:'#11688A',grey:'#BABABA',headingFont:'Sharp Sans Book / Semibold',bodyFont:'Satoshi Regular / Medium',
 fontRules:'Use the specified font files only if available and appropriately licensed. If absent, disclose the fallback and use Arial consistently. Do not claim that a brand font is embedded when it is not.',
 logoRules:'Use the approved supplied asset intact. Preserve aspect ratio and a clear area equal to the N in the logo on all sides. Select the colour logo for a white/light background and the white variant for a suitable dark background. Never stretch, crop, rotate, outline, recolour or recreate the logo. Avoid non-brand background colours and gradients behind it. The supplied stacked lockup is available; do not construct a horizontal replacement.',
 pageRules:'Proposed house layout: white pages with restrained NCGCL blue headings and selective green accents. For Word/PDF use A4 portrait and 20 mm margins unless the document-specific rules require otherwise. Keep whitespace deliberate. Use covers and contents only when appropriate to the document length or requested in the main brief. Keep a heading with its following paragraph and repeat header rows on multi-page tables. For HTML use a readable responsive content width and print styles. Slide dimensions are defined by the presentation rules.',
 textRules:'Proposed document hierarchy: 26–30 pt title, 17–20 pt first-level headings, 13–15 pt second-level headings and 10.5–11.5 pt body for Word/PDF. Use consistent named styles, approximately 1.15–1.3 line spacing and 6–8 pt paragraph spacing. Use bullets for parallel items and numbers for genuine sequences. Avoid decorative boxes around every paragraph. Adjust responsively for HTML; use presentation-specific sizes for slides. Do not shrink text to force a page count.',
 exhibitRules:'Use blue as the main data colour, green as selective emphasis, and neutral treatments for comparisons. Use distinctions beyond colour when needed. Every chart needs legible axes/units and a source where available. Tables should have a clear header, restrained rules, consistent alignment and units; avoid dense grids. Captions and exhibit numbering must be consistent. Follow the main prompt for factual sourcing; do not invent data or source lines to fill the design.',
 headerText:'',footerText:'NCGCL | {{title}} | {{page}}',
 footerRules:'Proposed footer: small, readable and understated, aligned consistently across pages. Show the confidentiality label when supplied. Use a distinct first-page layout where appropriate. No invented address, contact detail or legal disclaimer. Footer wording is a proposed house standard for the editor to finalise.',extra:'',
 types:[
 {id:'research-note',name:'Research note',description:'A focused analytical note.',formats:['Word (.docx)','HTML','PDF'],active:true,rules:'Adapt the benchmark’s clean typography, evidence-led exhibits and clear hierarchy using NCGCL colours. A concise title block usually suits a short note better than a separate cover. Use one column for short notes; use two columns only when readability benefits. Place wide exhibits near the relevant discussion. The main prompt determines the argument, headings and length.',extra:''},
 {id:'concept-note',name:'Concept note',description:'A proposition or proposed approach.',formats:['Word (.docx)','HTML','PDF'],active:true,rules:'Use a compact title block and clear numbered headings where useful. Distinguish proposed parameters, assumptions and agreed terms through labels. Apply consistent table styles to product parameters or comparisons. Use simple labelled transaction diagrams when requested; do not add sections or change the proposition solely for appearance.',extra:''},
 {id:'credit-proposal',name:'Credit proposal',description:'A credit or guarantee assessment.',formats:['Word (.docx)','HTML','PDF'],active:true,rules:'Use a formal title block, disciplined section hierarchy and consistent financial tables. Keep units, periods and decimal precision clear. Format decision requests, conditions and risk tables consistently when present. Preserve substantive terms and numerical values exactly; do not infer approvals or add covenants as a formatting exercise.',extra:''},
 {id:'research-paper',name:'Research paper',description:'A longer evidence-led publication.',formats:['Word (.docx)','HTML','PDF'],active:true,rules:'Use a restrained branded cover when warranted by the length, a consistent running footer, numbered exhibits and a clear reference style. Add a contents page only when useful. Use the supplied benchmark for visual hierarchy and exhibit treatment, never for copying prose, imagery or BCG identity. Preserve the main prompt’s structure and length.',extra:''},
 {id:'due-diligence',name:'Due-diligence report',description:'Findings, evidence and assessment.',formats:['Word (.docx)','HTML','PDF'],active:true,rules:'Keep finding labels, evidence references and table formatting consistent. Use accessible severity labels if supplied; do not invent severity ratings. Make annexures and cross-references easy to navigate. Preserve all numerical values and the stated assessment.',extra:''},
 {id:'executive-brief',name:'Executive brief',description:'A concise note for decision-makers.',formats:['Word (.docx)','HTML','PDF'],active:true,rules:'Use a compact title and metadata block, generous whitespace and a clear visual hierarchy. Do not add a cover or contents page to a short brief. Highlight only material takeaways already present in the content. Do not force a one-page limit unless requested.',extra:''},
 {id:'board-paper',name:'Board / committee paper',description:'A formal paper for governance meetings.',formats:['Word (.docx)','PDF'],active:true,rules:'Use a formal title block and a consistent treatment of meeting date, author and classification when supplied. Make decision or approval text visually distinct when present. Preserve approved wording and terms. Keep annexure labels and numbering consistent.',extra:''},
 {id:'offer-letter',name:'Offer / formal letter',description:'Institutional correspondence.',formats:['Word (.docx)','PDF'],active:true,rules:'Use a restrained letterhead with the approved logo, date, recipient, subject, body and signature blocks where supplied. Preserve approved commercial/legal wording. Do not add research-paper covers, chart treatments or promotional copy. Use only supplied address and signatory information.',extra:''},
 {id:'meeting-minutes',name:'Meeting minutes',description:'A record of discussions and actions.',formats:['Word (.docx)','HTML','PDF'],active:true,rules:'Apply clear meeting metadata and consistent headings. Format action items as a clean table where the content supplies owners and dates. Do not infer commitments, owners or deadlines. Keep footer and numbering understated.',extra:''},
 {id:'presentation',name:'PowerPoint presentation',description:'A branded slide deck.',formats:['PowerPoint (.pptx)','PDF'],active:true,rules:'Use 16:9 widescreen. Apply a consistent NCGCL title slide and content-slide system with safe margins, approved logo placement and slide numbering. Prefer titles around 28–36 pt and body around 18–24 pt; increase slide count rather than shrinking text. Use blue-led charts, green emphasis, concise captions and source lines. Use editable native elements where practical. The main prompt controls narrative, tone and slide count.',extra:''}
 ],
 assets:[
 {id:'logo-colour',name:'NCGCL colour logo',kind:'Logo',url:'/assets/ncgcl-logo.png',scopes:[],formats:[],attach:true,usage:'Use intact on white/light backgrounds.'},
 {id:'logo-white',name:'NCGCL white logo',kind:'Logo',url:'/assets/ncgcl-white-logo.png',scopes:[],formats:[],attach:false,usage:'Use intact on suitable dark backgrounds.'},
 {id:'brand-guide',name:'NCGCL Brand Guidelines v5',kind:'Brand guide',url:'/assets/ncgcl-brand-guidelines.pdf',scopes:[],formats:[],attach:false,usage:'Background reference for NCGCL identity, colours, typography and logo rules.'},
 {id:'benchmark',name:'Energy transition editorial benchmark',kind:'Benchmark',url:'/assets/energy-transition-benchmark.pdf',scopes:['research-note','concept-note','research-paper'],formats:[],attach:false,usage:'Reference for hierarchy and exhibit design only; do not copy BCG branding, imagery or text.'}
 ]};
